version: 2

jobs:
  deploy:
    docker:
      - image: devopsfnl/image:php-8.1-laravel-newman-xdebug3
      - image: postgres:9.6.2
    steps:
      - checkout
      - run:
          name: Heroku Dev App Deploy
          command: git push --force https://heroku:$HEROKU_VITE_KEY@git.heroku.com/$HEROKU_VITE_APP.git HEAD:refs/heads/master

  validate:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Docker compose up, in detatched/background mode
          command: docker-compose up -d
      - run:
          name: Composer install
          command: docker-compose exec vite-api composer install -n --prefer-dist
      - run:
          name: CI checks
          command: docker-compose exec vite-api composer run ci
      - run:
          name: Dev Setup
          command: docker-compose exec vite-api composer run dev-setup

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - validate:
          filters:
            branches:
              only:
                - vite
      - deploy:
          requires:
            - validate
